### ISSUE TITLE
Overview mode: not showing header

### ISSUE THREAD

**Issue by bakboord4** [maykar/custom-header#182] opened 2020-05-16 15:22 UTC
Testing HA 0110.0b3

In overview mode Lovalace is showing 1. a blanc header and 2. at bottom instead of at top . 
Unable to select f.i. Configuration UI or a sub view. See below photo is bottom part of window.
In HA 0.109 no problem.

<img width="1221" alt="Schermafbeelding 2020-05-16 om 17 03 21" src="https://user-images.githubusercontent.com/42673768/82123264-b6727900-9798-11ea-8e3b-d869ccd67921.png">

Logged Error message:
2020-05-16 16:57:16 ERROR (MainThread) [frontend.js.latest.202005150] http://ip.addr.ess :8123/hacsfiles/custom-header/custom-header.js:1:16344 TypeError: null is not an object (evaluating 'o[e].querySelector("paper-icon-button").style')

**Comment by bakboord4** [comment] 2020-05-16 15:33
additional info.

A copy/paste of your Custom Header config
no access to configuration UI
Any errors relevant to Custom Header found in the HA logs
see bug.
Any relevant errors found in your browsers dev console (usually found by hitting F12)
<img width="1333" alt="Schermafbeelding 2020-05-16 om 17 31 27" src="https://user-images.githubusercontent.com/42673768/82123723-2124b400-979b-11ea-9b9b-c0d8a88e2d86.png">

The version of Home Assistant and Custom Header you are using
1.3.8.
The browser type your are using
Safari latest version

**Comment by gadgetchnnel** [comment] 2020-05-17 09:50
Are you running the Home Assistant 0.110 beta? That error looks the same as [this issue](https://github.com/maykar/custom-header/issues/179) which is due to a change in the way 0.110 handles icons.

**Comment by bakboord4** [comment] 2020-05-17 13:25
@gadgetchnnel 
Beta?
Yes all the three 0.110.0beta versions sofar give the same problem.
reported issue?
For me difficult to answer.
At least the number of the last reported error is the same: 16344. 
If you think it is the same error, I will close the issue.

**Comment by bramkragten** [comment] 2020-05-20 11:49
duplicate of #179

**Closed by bramkragten** 2020-05-20 11:49 UTC
Labels: Bug
