### ISSUE TITLE
Uncaught ReferenceError: header is not defined

### ISSUE THREAD

**Issue by jo-me** [maykar/custom-header#241] opened 2020-07-20 10:35 UTC
Hi,

I'm seeing these in the log all the time:

```
Protokolldetails ( ERROR )
Logger: frontend.js.latest.202007021
Source: components/system_log/__init__.py:209
First occurred: 10:54:03 (47 occurrences)
Last logged: 12:26:03

https://hostname:8123/hacsfiles/custom-header/custom-header.js:617:8350 Uncaught ReferenceError: header is not defined
```

Header seems to work though. Not sure which functionality is affected by that error mesasge.

Any idea what is causing this?

I'm running latest custom-header 1.6.7 (via HACS) on latest Home Assistant 0.112.4.

Config:
```
custom_header:
  button_text:
    menu: menu
    options: '{{ time }}<br>{{ date }}'
    voice: voice<br>button
  compact_mode: true
  hide_help: true
  restrict_users: true
  voice_hide: true
```

**Comment by maykar** [comment] 2020-07-21 12:21
Not sure how this is the first I'm hearing about this, but thank you. This is caused by a typo and I'll have it fixed in the next release.

**Comment by maykar** [comment] 2020-08-06 12:09
Please try the latest release (1.6.8) and report back.

**Closed** 2020-08-08 15:35 UTC
Labels: Bug
