### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by jimz011** [maykar/custom-header#181] opened 2020-05-15 04:25 UTC
Hi Mayker, I know you have been busy and it is why I have waited a bit to send this in (as it seems no one else has this problem. Since your HA 107 fixes I get this error and custom header will simply not load. Even pressing reload resources would do nothing. I even tried with zero options configured in custom header except "hide_header: true". This seems to not work either. It does work if I use a few views, but the moment I use more views than a few it stops loading on a refresh.

It is rather strange as I get these errors without any config except the one mentioned above. What is even stranger is, that if I use an empty dashboard as standard with a button to my current dashboard, it will load up fine. However it won't load on the standard dashboard either. I have actually opted for multiple dashboards because of this. If I only use one dashboard custom-header will not load at all. All other cards seem to load fine, it is just CH that isn't loading up. I hope this might help you as I have tried to find the error myself, but I am not a programmer unfortunately.
```
https://MYDOMAIN/hacsfiles/custom-header/custom-header.js:1:16344 Uncaught TypeError: Cannot read property 'style' of null
https://MYDOMAIN/frontend_latest/chunk.62e2169407b0bea05071.js:1446:318 Uncaught TypeError: Cannot read property 'replaceChild' of null
```

Thanks for the help and take your time, no need to rush we all appreciate the hard work that has gone into this.

**Comment by roblamoreaux** [comment] 2020-05-16 16:16
I am seeing this as well. with the exact same error. I suspected it may be that I am running HASS 0.110.0b2. I'll see if it persists after updating to HASS 0.110.0b3

**Comment by user897943** [comment] 2020-05-20 11:22
Same error. Now I have to press F5 to refresh the page and if I'm quick enough I can click on the hamburger menu to open my settings page, but the header is gone and I cannot move to my other views now. 0.100.10 has just been released on DockerHub and it is the latest version, I am not running the dev version.

**Comment by bramkragten** [comment] 2020-05-20 11:48
duplicate of #179

**Closed by bramkragten** 2020-05-20 11:48 UTC
Labels: Bug
