### ISSUE TITLE
Auto-Switch Tabs (Cycle) based on a Delay

### ISSUE THREAD

**Issue by UbhiTS** [maykar/custom-header#249] opened 2020-08-18 23:43 UTC
Is there a possibility of adding a feature that allows to auto switch between tabs  :-

auto_switch_tabs:
    start_after: 300 # starts the auto tab switching if idle for 5 minutes
    delay: 30 # switches tabs every X seconds
    tabs: # tab sequence to switch
    - 5 to 9
    - 0
    - home

I basically want to have a dedicated android tablet kiosk for my home which switches screens every X seconds to show various different views of my HA setup.

> Weather Screen
> Calendar Screen
> Devices "ON" in the House
> Energy Profile Screen - Solar, Battery, Grid, Home
> Internet Speed Graph
> Floorplan
> NAS Status etc.

I really feel it would be an amazing feature to have in Custom Header. What do you think ?

Thanks

**Comment by maykar** [comment] 2020-08-19 00:07
Duplicate of #227. Please see that issue for a solution.

**Closed by maykar** 2020-08-19 00:07 UTC
Labels: Duplicate, Feature Request
