### ISSUE TITLE
Tab icons only for small devices

### ISSUE THREAD

**Issue by Alexxander0** [maykar/custom-header#135] opened 2020-02-19 15:26 UTC
Hi,

would be awesome if its possible to use icons for the tabs on small devices only, otherwise a text for the tab.

Thanks!

**Comment by maykar** [comment] 2020-03-29 14:32
Going to call this one a duplicate of #58 as once that is implemented then you'd be able to make an mobile exception using that new feature.

**Closed by maykar** 2020-03-29 14:32 UTC
Labels: Feature Request
