### ISSUE TITLE
Changing tabs using “path” service broken

### ISSUE THREAD

**Issue by dmatik** [maykar/custom-header#118] opened 2020-01-26 06:28 UTC
Hi,
Since todays several updates, not sure which one exactly since I updated them all and only then noticed, there a glitch when moving from tab to tab using the go to path service. 
I have such buttons in my lovelace design, and they just started doing it today. 
Have them working fine for months until now. 
The screenshot would not help here, only video. And there is no such option. Sorry for that.

**Comment by maykar** [comment] 2020-01-26 07:13
If I understand you correctly, you have a button that navigates to the path of another view. Is that view hidden? If it is hidden do you have `hidden_tab_redirect` set to false?

**Comment by dmatik** [comment] 2020-01-26 07:31
Hi,
Thanks for quick response. 
Nope, no hidden views. 
I have the main view with button that redirect to most of other views. Have this working for along time. 
Switching between views using the header itself seems to be working fine. 
Also seems that the issue is happening only on iPhone and not on PC’s browser.

**Comment by dmatik** [comment] 2020-01-26 07:59
Also... this issue is only on iPhone’s official companion app...
Even on Safari browser on the same iPhone it works just fine.

**Comment by PostSven** [comment] 2020-01-26 08:36
same issue here, the whole ios app is glitching back and forth when tapping a button using the navigate path.

                  - tap_action:
                      action: navigate
                      navigation_path: /lovelace/lampen
                      haptic: light

**Comment by browetd** [comment] 2020-01-26 10:56
Not sure if this is related but if, from my main tab, I click on a button with a path to a hidden tab, HA comes back immediately to the main tab (phone and PC, same behaviour)...  If I choose to display permanently the "hidden" tab, it stays on it...  Maybe be due to the fact that on my main tab, I have entities updated every second... I had that in a previous version of Custom Header but it was fixed at that time... If not related to the current issue, let me know and I open a new issue.

**Comment by maykar** [comment] 2020-01-26 14:49
If you're having this issue, please provide your Custom-Header config.

**Comment by PostSven** [comment] 2020-01-26 15:13
Hi, see info below:

`Home Assistant 0.104.3`

`http://myurl/frontend_latest/app.ecb6dd07.js:726:267614 SecurityError: Attempt to use history.pushState() more than 100 times per 30 seconds`

```
custom_header:
  compact_mode: true
  hide_header: true
and
custom_header:
  compact_mode: true
  hide_header: true

resources:
  - url: /community_plugin/custom-header/custom-header.js
     type: module
```

Only seems to happen on IOS devices.

**Comment by maykar** [comment] 2020-01-26 15:26
I am able to reproduce. Bear with me as the only iOS and Mac setups I have are ancient. Makes troubleshooting a slow and painful process.

**Comment by PostSven** [comment] 2020-01-26 15:31
> I am able to reproduce. Bear with me as the only iOS and Mac setups I have are ancient. Makes troubleshooting a slow and painful process.

Check! Thanks for the quick reply

**Comment by Knapoc** [comment] 2020-01-26 15:35
I'm experiencing the same issue.

My config for custom-header:
```
custom_header:
  compact_mode: true
  voice_hide: true
  hide_config: true
  hide_tabs:
   - plants
   - settings
```

Happens with multiple browser: chrome, firefox and safari.
As soon as I unhide the tabs, path redirects via buttons work again.

**Comment by PostSven** [comment] 2020-01-26 15:38
> I'm experiencing the same issue.
> 
> My config for custom-header:
> 
> ```
> custom_header:
>   compact_mode: true
>   voice_hide: true
>   hide_config: true
>   hide_tabs:
>    - plants
>    - settings
> ```
> 
> Happens with multiple browser: chrome, firefox and safari.
> As soon as I unhide the tabs, path redirects via buttons work again.

You probably have a different issue, add 

hidden_tab_redirect: false

To your config

**Comment by Knapoc** [comment] 2020-01-26 15:53
I already tried this. Fixes it in firefox & chrome but in safari I get continuous redirects between to views

**Comment by PostSven** [comment] 2020-01-26 15:55
> I already tried this. Fixes it in firefox & chrome but in safari I get continuous redirects between to views

Yes you are facing 2 issues.

1 is fixed with the config change, and the other one is a bug at this moment

**Comment by jimz011** [comment] 2020-01-26 17:07
I also have `hidden_tab_redirect: false` (but I already had that). But I don't think that is the issue. It just lives its own life when navigating to a hidden tab (with the above setting yes).

I even got it as far as moving back and forth between 5 views. My UI wasn't responding at all so I pressed multiple buttons after each other. After a second or 10 it started doing something again, but now it would just rotate between those 5 views that I have selected earlier. It gets even more funny:
When I open the app again after 15/30 minutes or so. It just continues what it was doing (so rotating between those views).

I also found that when going to another tab, it often loses connection and wants to reconnect (it will show the yellow cog at the bottom right of the screen on the ios app. When this happens the UI will refresh, but most of the UI will then become unreponsive, you could still scroll. But pressing a button would do nothing until you either waited long enough or refresh)

**Comment by dmatik** [comment] 2020-01-26 17:27
1.3.1 seems to be fixing the issue with go to path of the view. 
Thank you very much for quick resolution!

**Comment by PostSven** [comment] 2020-01-26 17:52
installed 1.3.1 the disco mode flickering is gone (so far) i will keep testing!

**Closed** 2020-01-27 01:09 UTC
Labels: Bug
