### ISSUE TITLE
When voice not defined in configuration.yaml, custom-header.js 

### ISSUE THREAD

**Issue by dooz127** [maykar/custom-header#28] opened 2019-12-16 17:34 UTC
I normally hide the voice button but did not update that setting when I ported over from cch to custom-header so I got the following error:

```
2019-12-16 08:13:52 ERROR (MainThread) [frontend.js.latest.201912041] https://hass.local:8123/community_plugin/custom-header/custom-header.js:576:42389 TypeError: undefined is not an object (evaluating '_.voice.style')
```

**Comment by maykar** [comment] 2019-12-16 17:38
Duplicate of https://github.com/maykar/custom-header/issues/21

Looking into it now.

**Closed by maykar** 2019-12-16 17:38 UTC
Labels: bug, duplicate

**Comment by dooz127** [comment] 2019-12-16 17:42
Sorry about that, didn't see that one.
