### ISSUE TITLE
Auto-justify header tabs/icons

### ISSUE THREAD

**Issue by vitaalz** [maykar/custom-header#250] opened 2020-08-20 09:39 UTC
Hello, 

Is it possible to implement the feature where header tab/icon alignment can be automatically justified so their placement take the whole screen proportionally? This would be useful in cases if there are not that many tabs. 

![alignment](https://user-images.githubusercontent.com/36511802/90753993-f5f1b980-e2e1-11ea-9c45-45fc6de2292c.png)

**Comment by maykar** [comment] 2020-08-25 13:54
Duplicate of #134 and #198

**Closed by maykar** 2020-08-25 13:54 UTC
Labels: Feature Request

**Comment by maykar** [comment] 2020-09-23 13:46
This is now possible with the new fit tabs feature `fit_tabs: true`. This would accomplish what I believe you were going for. If, however, you wanted them to be centered in the middle of the header you can use some custom css. You may need to adjust the width to your needs with percent or pixel sizes:

With percent:
```
  fit_tabs: true
  tab_container_css: 'width: 50% !important; margin: auto !important;'
```

With pixels:
```
  fit_tabs: true
  tab_container_css: 'width: 400px !important; margin: auto !important;'
```
